[build]
  # Build qilganda qaysi buyruq ishlatiladi
  command = "npm run build"

  # Build natijasi joylashadigan papka (CRA -> build, Vite -> dist)
  publish = "dist"

# SPA routing uchun redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
